name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker login --username bappeda-dev-team --password ${{ secrets.GH_TOKEN }} ghcr.io
          docker build --build-arg NEXT_PUBLIC_API_URL=https://api-espbe.kertaskerja.cc . --file Dockerfile --tag ghcr.io/bappeda-dev-team/espbe-kota-madiun-frontend:latest
          docker push ghcr.io/bappeda-dev-team/espbe-kota-madiun-frontend:latest
